packages:
  - .

allowBuilds:
  esbuild: false
  unrs-resolver: false

blockExoticSubdeps: true

minimumReleaseAge: 10080 # 7 days in minutes

minimumReleaseAgeExclude:
  - pnpm@11.21.0
  - js-yaml@4.3.1

overrides:
  js-yaml@>=4.0.0 <4.3.1: ^4.3.1
  semver: '>=7'

publishBranch: main

strictPeerDependencies: false

trustPolicy: no-downgrade
