autoInstallPeers: true

enablePrePostScripts: true

legacyPeerDeps: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver

overrides:
  chalk@<5.6.2: '>=5.6.2'
  seroval@<1.4.1: '>=1.4.1'
  seroval@<=1.4.0: '>=1.4.1'

strictPeerDependencies: false
