autoInstallPeers: true

enablePrePostScripts: true

legacyPeerDeps: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver

overrides:
  '@eslint/eslintrc>ajv': ^6.12.4
  ajv@<8.18.0: '>=8.18.0'
  eslint>ajv: ^6.12.4
  chalk@<5.6.2: '>=5.6.2'
  seroval@<1.4.1: '>=1.4.1'

strictPeerDependencies: false
